Fix python header include
http://docs.python.org/c-api/intro.html#includes says:

-------------------
Since Python may define some pre-processor definitions which affect
the standard headers on some systems, you must include Python.h before
any standard headers are included.
-------------------

Here is the build error:

pygtk-codegen-2.0 --prefix zynjacku_c \
        --register `pkg-config --variable=defsdir pygtk-2.0`/gdk-types.defs \
        --register `pkg-config --variable=defsdir pygtk-2.0`/gtk-types.defs \
        --override zynjacku.override \
        zynjacku.defs > zynjacku_wrap.c
note: pygtk-codegen-2.0 is deprecated, use pygobject-codegen-2.0 instead
note: I will now try to invoke pygobject-codegen-2.0 in the same directory
In file included from /usr/include/python2.6/Python.h:8,
                 from ttl.l:2:
/usr/include/python2.6/pyconfig.h:1052:1: error: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdio.h:28,
                 from flex_ttl.c:20:
/usr/include/features.h:210:1: error: this is the location of the previous definition
make[1]: *** [flex_ttl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
Could not write function zynjacku_lv2_load: No ArgType for const-LV2_Feature*-const*
Could not write function zynjacku_lv2_unload: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_connect_port: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_run: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_activate: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_deactivate: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_get_descriptor: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_get_handle: No ArgType for zynjacku_lv2_handle
Could not write function zynjacku_lv2_message: No ArgType for zynjacku_lv2_handle
***INFO*** The coverage of global functions is 40.00% (6/15)
***INFO*** The coverage of methods is 100.00% (46/46)
***INFO*** There are no declared virtual proxies.
***INFO*** There are no declared virtual accessors.
***INFO*** There are no declared interface proxies.